version: '3.9'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xdd123456
      MYSQL_DATABASE: xdd-api
      MYSQL_USER: xdd_user
      MYSQL_PASSWORD: xdd123456
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    ulimits:
      nofile:
        soft: 20000
        hard: 40000

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - '3006:8080'
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  mysql_data: {}
